### PR TITLE
Unbreak build with OpenAL 1.20.0

### PR DESCRIPTION
**Pull request by t6**
```
In file included from /home/tobias/src/github.com/uTox/uTox/src/av/audio.c:33:
/usr/local/include/AL/alc.h:34:26: error: typedef redefinition with different types
      ('struct ALCdevice' vs 'struct ALCdevice_struct')
typedef struct ALCdevice ALCdevice;
                         ^
/home/tobias/src/github.com/uTox/uTox/src/av/audio.h:8:33: note: previous definition is here
typedef struct ALCdevice_struct ALCdevice;
                                ^
1 error generated.
```

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1401)

### CODE REVIEW

**Comment by GrayHatter** [comment]
:lgtm:

**Comment by avoidr** [comment]
Thanks!
